# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake

# The command to remove a file.
RM = /theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /sulb0/rcostari/rtos_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /sulb0/rcostari/rtos_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/theia/home/apps/CO7/skylake/software/CMake/3.15.3-GCCcore-8.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /sulb0/rcostari/rtos_2/CMakeFiles /sulb0/rcostari/rtos_2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /sulb0/rcostari/rtos_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mastermind_hydra

# Build rule for target.
mastermind_hydra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mastermind_hydra
.PHONY : mastermind_hydra

# fast build rule for target.
mastermind_hydra/fast:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/build
.PHONY : mastermind_hydra/fast

Challenger.o: Challenger.cpp.o

.PHONY : Challenger.o

# target to build an object file
Challenger.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Challenger.cpp.o
.PHONY : Challenger.cpp.o

Challenger.i: Challenger.cpp.i

.PHONY : Challenger.i

# target to preprocess a source file
Challenger.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Challenger.cpp.i
.PHONY : Challenger.cpp.i

Challenger.s: Challenger.cpp.s

.PHONY : Challenger.s

# target to generate assembly for a file
Challenger.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Challenger.cpp.s
.PHONY : Challenger.cpp.s

Evaluation.o: Evaluation.cpp.o

.PHONY : Evaluation.o

# target to build an object file
Evaluation.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Evaluation.cpp.o
.PHONY : Evaluation.cpp.o

Evaluation.i: Evaluation.cpp.i

.PHONY : Evaluation.i

# target to preprocess a source file
Evaluation.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Evaluation.cpp.i
.PHONY : Evaluation.cpp.i

Evaluation.s: Evaluation.cpp.s

.PHONY : Evaluation.s

# target to generate assembly for a file
Evaluation.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Evaluation.cpp.s
.PHONY : Evaluation.cpp.s

Gamemaster.o: Gamemaster.cpp.o

.PHONY : Gamemaster.o

# target to build an object file
Gamemaster.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Gamemaster.cpp.o
.PHONY : Gamemaster.cpp.o

Gamemaster.i: Gamemaster.cpp.i

.PHONY : Gamemaster.i

# target to preprocess a source file
Gamemaster.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Gamemaster.cpp.i
.PHONY : Gamemaster.cpp.i

Gamemaster.s: Gamemaster.cpp.s

.PHONY : Gamemaster.s

# target to generate assembly for a file
Gamemaster.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Gamemaster.cpp.s
.PHONY : Gamemaster.cpp.s

Guess.o: Guess.cpp.o

.PHONY : Guess.o

# target to build an object file
Guess.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Guess.cpp.o
.PHONY : Guess.cpp.o

Guess.i: Guess.cpp.i

.PHONY : Guess.i

# target to preprocess a source file
Guess.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Guess.cpp.i
.PHONY : Guess.cpp.i

Guess.s: Guess.cpp.s

.PHONY : Guess.s

# target to generate assembly for a file
Guess.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Guess.cpp.s
.PHONY : Guess.cpp.s

Range.o: Range.cpp.o

.PHONY : Range.o

# target to build an object file
Range.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Range.cpp.o
.PHONY : Range.cpp.o

Range.i: Range.cpp.i

.PHONY : Range.i

# target to preprocess a source file
Range.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Range.cpp.i
.PHONY : Range.cpp.i

Range.s: Range.cpp.s

.PHONY : Range.s

# target to generate assembly for a file
Range.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Range.cpp.s
.PHONY : Range.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mastermind_hydra.dir/build.make CMakeFiles/mastermind_hydra.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mastermind_hydra"
	@echo "... edit_cache"
	@echo "... Challenger.o"
	@echo "... Challenger.i"
	@echo "... Challenger.s"
	@echo "... Evaluation.o"
	@echo "... Evaluation.i"
	@echo "... Evaluation.s"
	@echo "... Gamemaster.o"
	@echo "... Gamemaster.i"
	@echo "... Gamemaster.s"
	@echo "... Guess.o"
	@echo "... Guess.i"
	@echo "... Guess.s"
	@echo "... Range.o"
	@echo "... Range.i"
	@echo "... Range.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

